name: CI

on:
  push:
    branches: [main, kperf-macos]

  pull_request:
    branches: [main]

jobs:
  exe:
    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: 'poop'

      - name: Clone scoop repository
        run: git clone https://codeberg.org/tensorush/scoop.git

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Build scoop
        continue-on-error: true
        run: cd scoop && zig build

      - name: Build poop
        run: cd poop && zig fetch --save ../scoop && zig build

  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Run fmt step
        run: zig build fmt
